version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    hostname: web
    restart: always
    ports:
      - 3000:3000
    environment:
      - API_URL=https://api.beta.svfoundation.org.ua/
    entrypoint: ["node", "server.js"]

